### ISSUE TITLE
InfluxbDB crash

### ISSUE THREAD

**Issue by fabiencharrasse** [aceberg/WatchYourLAN#105]
Hello,

I just installed your app and everything worked until i fill the influxdbform : (the container keep crash / restart until i disable influxdb export)

[debug.log](https://github.com/user-attachments/files/16826257/debug.log)

Thanks !

**Comment by aceberg** [comment]
I added more InfluxDB error checks in v2.0.1. Hope this will make the error more specific.

**Comment by fabiencharrasse** [comment]
Thanks ! The app seems to not crash anymore. 
The log has changed : 

> 2024/09/02 18:34:51 ERROR parse "x.x.x.x:8086/": first path segment in URL cannot contain  #colon
> 2024/09/02 18:34:51 ERROR Can't connect to InfluxDB server

What's the problem with my influxdb host ?

**Comment by aceberg** [comment]
> parse "x.x.x.x:8086/": first path segment in URL cannot contain #colon

Looks like the Address should start with `http://` or `https://`

**Comment by fabiencharrasse** [comment]
Thanks it's fixed now.
