### ISSUE TITLE
Windows version wanted

### ISSUE THREAD

**Issue by iigx** [aceberg/WatchYourLAN#133]
I'm using a low power windows host as a NAS, 7*24 hours a day.
I would like to be able to run WatchYourLan on this machine.
If I can get a compiled windows version, I'd appreciate it!

**Comment by aceberg** [comment]
WatchYourLAN uses Linux tool `arp-scan` to scan the network, so it will not work on Windows. 
Though, I think, Docker image should work, if you specify IFACES correctly.
