### ISSUE TITLE
Documentation and examples for notifications

### ISSUE THREAD

**Issue by cyberbrix** [aceberg/WatchYourLAN#134]
Is there any documentation or examples for using the Shoutrrr URL? Perhaps what variables to use, syntax, etc?

I used a webhook <url>, which worked as a curl, but when I put it in as generic+<url>, it failed.

**Comment by aceberg** [comment]
There is a link to Shoutrrr documentation on Config page of WYL: https://containrrr.dev/shoutrrr/v0.8/

**Comment by cyberbrix** [comment]
I followed the documentation and received the following error.

2024/09/17 13:46:44 ERROR Notification failed (shoutrrr):  ""="an error occurred while sending notification to generic webhook: server returned response status code 400 Bad Request"

my 

`generic+https://api.pushover.net/1/messages.json?token=<REDACTED>&user=<REDACTED>title=Unknown+host+detected&message=test+message`

I don't use shoutrrr, so I used the "generic" nomenclature.

The command works perfectly fine if I curl it.

It would be great to have some examples and list the variables/info we can include in our message.

**Comment by aceberg** [comment]
> It would be great to have some examples and list the variables/info we can include in our message.
Here is an example for `pushover`:
https://containrrr.dev/shoutrrr/v0.8/services/pushover/

**Comment by cyberbrix** [comment]
So this is to my point. The documentation says:

> Link to any notification service supported by Shoutrrr (gotify, email, telegram and others) or Generic Webhook

The link goes to [Shoutrrr](https://github.com/containrrr/shoutrrr/blob/main/docs/services/generic.md)

and says to use generic+<URL>

I'm not using Shoutrrr. So an example would be helpful for how to put in a generic webhook.

**Comment by aceberg** [comment]
Shoutrrr is already inside WatchYourLAN as a module. You don't need to install it, just use the example in Shoutrrr doc.

**Comment by cyberbrix** [comment]
Oh, definitely didn't realize that. 
Are there variables we can reference for the message?

**Comment by aceberg** [comment]
> Are there variables we can reference for the message?

Not yet.
