### ISSUE TITLE
Couldn't find your contact info soooo...

### ISSUE THREAD

**Issue by dnburgess** [aceberg/WatchYourLAN#14]
Really digging this container. So I made a video about it on my YouTube channel: https://youtu.be/DknqJrnlLQo

People seem to enjoy it!

Also, are there any plans to fix the IP sorting order that I show in the video?

**Comment by aceberg** [comment]
@dnburgess, wow! The video is awesome! Thanks for promoting WatchYourLAN like that))

The IP sorting is fixed now, I think (It's available on separate pages `Online` and `Offline`. `Home` page is sorted by date still.

**Comment by dnburgess** [comment]
That's awesome!! Glad you got the sorting taken care of!!
