### ISSUE TITLE
Column Sort bug in Chrome

### ISSUE THREAD

**Issue by aceberg** [aceberg/WatchYourLAN#140]
This seems to work in Firefox but not in Chrome for me. Not sure if this is known (or if its just my browser). Not a huge deal but wanted to make you aware.

_Originally posted by @rw377 in https://github.com/aceberg/WatchYourLAN/issues/87#issuecomment-2371933626_

**Comment by gabrielwhite** [comment]
I am also having this issue in Brave / Chrome (MacOS) - cannot sort columns.

**Comment by gabrielwhite** [comment]
Update: I think the issue is somewhere in the JavaScript code here that handles sorting. The IP sorting column works, but none of the others do.

```
function sortByAny(someArray) {

    if (field == 'IP') {
        someArray.sort((a, b) => sortIP(a, b, down));
    } else {
        someArray.sort((a, b) => byField(a, b, field, down));
    }

    displayArrayData(someArray);
}

function byField(a, b, fieldName, down){
    if (a[fieldName] > b[fieldName]) {
        return down;
    } else {
        return !down;
    }
}
```
