### ISSUE TITLE
Add notification test

### ISSUE THREAD

**Issue by robled** [aceberg/WatchYourLAN#147]
I saw a screenshot of a version with a "test notification" button, but perhaps it was removed in a more recent version.  This option is very helpful for initial configuration, especially for notification services that require authentication.

**Comment by jayjoshi64** [comment]
I second this request.  I am getting hard time getting to work with notifications.   till now, all I ready is that it's supported by shoutrrr, nothing else.    it would be good if there's a test notification button... and also some sort of config/description on what sort of notifications are actually supported?  I have no clue what to expect from it.  some examples would be great.
