### ISSUE TITLE
IP address sorting weirdness?

### ISSUE THREAD

**Issue by malventano** [aceberg/WatchYourLAN#18]
As seen in [this video](https://youtu.be/DknqJrnlLQo?t=147), IP address sorting appears to be misbehaving. Is this correctable or is it a bug in a different library?

**Comment by aceberg** [comment]
@malventano It's already fixed in the 0.7.5 version (latest). Please, update your docker image

**Comment by SigHunter** [comment]
I'm using latest docker image (aceberg/watchyourlan latest 0817d8d1c1b5) and this is still the case

"Log" and "online" tables still sort weird, not by real numbers and not by absolute numbers (whatever this is called). I have a new install, just some hours old.

![grafik](https://user-images.githubusercontent.com/8151315/191464622-10237c67-5bfe-49cb-808d-2f227cc0b257.png)

**Comment by crispybegs** [comment]
> I'm using latest docker image (aceberg/watchyourlan latest 0817d8d1c1b5) and this is still the case
> 
> "Log" and "online" tables still sort weird, not by real numbers and not by absolute numbers (whatever this is called). I have a new install, just some hours old.
> 
> ![grafik](https://user-images.githubusercontent.com/8151315/191464622-10237c67-5bfe-49cb-808d-2f227cc0b257.png)

was there ever a fix for this? i just installed WYL and i really like it, but the disorganised IP sorting makes it frustrating.
