### ISSUE TITLE
WSL2 subnet configuration

### ISSUE THREAD

**Issue by graphixillusion** [aceberg/WatchYourLAN#20]
Hi there. I'm trying this under WSL2 in Windows 10. The iface name under WSL2 is "eth0" but if i scan the "eth0" i get only that subnet. Is there any way to scan the original Windows subnet? Thank you

**Comment by sholder89** [comment]
I went down this same rabbit hole this morning! Apparently it can't be done at least not easily since Windows isolates the networking of docker on WSL.

Some more info here: https://github.com/docker/for-win/issues/6736
