### ISSUE TITLE
Buttons do not work with Opera browser.

### ISSUE THREAD

**Issue by Teleportist** [aceberg/WatchYourLAN#22]
Pressing any button (sorting or yes/no) on the web interface returns an 'ERR_TOO_MANY_REDIRECTS' page when using Opera browser.
Edge browser is fine.

**Comment by aceberg** [comment]
> Pressing any button (sorting or yes/no) on the web interface returns an 'ERR_TOO_MANY_REDIRECTS' page when using Opera browser. Edge browser is fine.

I'm not sure it's WatchYourLAN problem. Just tried it in Opera browser and got no errors. Maybe there are other redirects like reverse proxy in your setup? Or it's something Windows is doing (I do not have Windows to test on it)
