### ISSUE TITLE
Using docker, the host is not founded

### ISSUE THREAD

**Issue by lubomben** [aceberg/WatchYourLAN#23]
Using docker image on my Raspberry with "host" network mode, all devices are founded except the raspberry itself.

I am using "eth0" as interface to scan.

**Comment by jhalbrecht** [comment]
Same, except that I'm running on a rocky linux 9 vm in proxmox. WYL is not listing the VM of the host VM that is running docker where WYL is running.

**Comment by ridhamdave** [comment]
Facing same issue. Am running WYL via Wifi Interface, and just the Host device is not found.

**Comment by aceberg** [comment]
That's normal behavior for any network scanner, actually. I don't think it needs to change
