### ISSUE TITLE
Shoutrrr is not working with my telegram chat

### ISSUE THREAD

**Issue by celesduran** [aceberg/WatchYourLAN#24]
I get the URL using "docker run --rm -it containrrr/shoutrrr generate telegram", and I put it in the container configuration, but I do not receive any message from telegram.

Any ideas?

**Comment by samcro1967** [comment]
I have been unable to get Gotify to work either.

**Comment by aceberg** [comment]
Notifications are only sent when a new device appears in the network. Maybe that's why you are not getting them
