### ISSUE TITLE
Feature request: track changes by MAC address

### ISSUE THREAD

**Issue by martinfrancois** [aceberg/WatchYourLAN#25]
Every time a device with the same MAC address is receiving a new ip address through DHCP, it shows up as an unknown entry. A configurable option would be nice which would set the status of new entries having a known MAC address in a different entry to be known.

Even better would be if the MAC address was used as a primary identifier (meaning there would only be one entry per MAC address, not per IP and MAC combination), and clicking on one would show the history of previous IP's and dates.

**Comment by savonarola27** [comment]
Same issue for me. A device should record the name even if his IP address change if the MAC address is the same.

**Comment by wangeris** [comment]
+1

**Comment by markus-li** [comment]
Not sure if any of our votes count, but considering what is truly important is to detect new HW being added, I'd add one more:
+1

**Comment by jamesmyatt** [comment]
This seems like basic functionality

**Comment by wangeris** [comment]
I'd be up for implementing it, but I can see that other Pull Requests with requested features were Closed, so makes me hesitant to invest time into the project

**Comment by sholder89** [comment]
> I'd be up for implementing it, but I can see that other Pull Requests with requested features were Closed, so makes me hesitant to invest time into the project

Unfortunately seems like the dev abandoned this project. @reneManqueros has a fork here that has some additional features, maybe they'd be willing to implement the change on their fork? https://github.com/reneManqueros/WatchYourLAN

**Comment by bugbounce** [comment]
The changes for this are committed in my fork at  https://github.com/bugbounce/WatchYourLAN/commit/7ca8feeec98589640dc091424c91c862bdc13974

Although I have no easy way of testing it. But its a simple enough change. @reneManqueros Please check  the code and pull if makes sense to you. I will raise a PR once I have update the Readme.

**Comment by barart** [comment]
+1 on this...

So this project is abandoned?

**Comment by aceberg** [comment]
Added option to ignore IP change. Set `IGNOREIP="yes"` to use it

**Comment by barart** [comment]
After update to this version im unable to start the container, im getting this error:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./watchyourlan": stat ./watchyourlan: no such file or directory: unknown`

**Comment by aceberg** [comment]
> After update to this version im unable to start the container, im getting this error:
> 
> `Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./watchyourlan": stat ./watchyourlan: no such file or directory: unknown`

Are you building your own docker image? Because in this release Dockerfile there is `WatchYourLAN` instead of `watchyourlan`

**Comment by barart** [comment]
> 
> Are you building your own docker image? Because in this release Dockerfile there is `WatchYourLAN` instead of `watchyourlan`

Nope, i getting the image directly from: https://hub.docker.com/r/aceberg/watchyourlan

I just upgraded it running the image from that url

**Comment by aceberg** [comment]
> Nope, i getting the image directly from: https://hub.docker.com/r/aceberg/watchyourlan
> 
> I just upgraded it running the image from that url

Can you show me the output of `docker inspect wyl | grep -i watch` ?
And maybe try to restart docker service?

**Comment by barart** [comment]
> 
> Can you show me the output of `docker inspect wyl | grep -i watch` ?
> 
> And maybe try to restart docker service?

Here you are:

docker inspect WatchLan | grep -i watch    
        "Path": "./watchyourlan",
            "Error": "failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"./watchyourlan\": stat ./watchyourlan: no such file or directory: unknown",
        "Name": "/WatchLan",
                "/home/WatchLan/data:/data"
                "Source": "/home/WatchLan/data",
            "Image": "aceberg/watchyourlan:latest",
                "./watchyourlan"

**Comment by aceberg** [comment]
> > Can you show me the output of `docker inspect wyl | grep -i watch` ?
> > And maybe try to restart docker service?
> 
> Here you are:
> 
> docker inspect WatchLan | grep -i watch "Path": "./watchyourlan", "Error": "failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./watchyourlan": stat ./watchyourlan: no such file or directory: unknown", "Name": "/WatchLan", "/home/WatchLan/data:/data" "Source": "/home/WatchLan/data", "Image": "aceberg/watchyourlan:latest", "./watchyourlan"

Ok, it looks like docker using the old lowcase path somehow. I think deleting the container and creating a new one should help.
On my servers (Ubuntu and Debian, amd64) the update went flawlessly, so, maybe, it's the version of docker you are using, I'm not sure.

**Comment by barart** [comment]
> 
> Ok, it looks like docker using the old lowcase path somehow. I think deleting the container and creating a new one should help. On my servers (Ubuntu and Debian, amd64) the update went flawlessly, so, maybe, it's the version of docker you are using, I'm not sure.

I see, for some reason even when recreating it, the Entrypoint record was not updated, i changed it and recreate the container and it worked

Thanks a lot!
