### ISSUE TITLE
Feature Request: Button to clear log

### ISSUE THREAD

**Issue by RichyHBM** [aceberg/WatchYourLAN#26]
As per the title, a way to clear the log of old devices would be useful!

**Comment by Teleportist** [comment]
+1

Maybe ad additional 'edit' buttons next to each entry, pointing to a delete option. Would make it less easy to accidentally delete one or all entries.

**Comment by savonarola27** [comment]
+1

**Comment by GentleHoneyLover** [comment]
+1

**Comment by schniggie** [comment]
+1

**Comment by wangeris** [comment]
+1

**Comment by bugbounce** [comment]
https://github.com/aceberg/WatchYourLAN/pull/35

**Comment by jeffreyswiggins** [comment]
Another request for an option to delete hosts

**Comment by Sylvio82** [comment]
I would like to have this feature, too!

**Comment by Sylvio82** [comment]
Hi.
Thanks for the quick reply. I am using WatchYourLAN with docker on my
synology nas. Where can I see which version I am using? I updated my docker
container yesterday and can see the config page, but there is no clear
table button nor can I delete a host.

regards Sylvio

Am Di., 3. Jan. 2023 um 12:53 Uhr schrieb Andrew Erlikh <
***@***.***>:

**Comment by aceberg** [comment]
> Hi. Thanks for the quick reply. I am using WatchYourLAN with docker on my synology nas. Where can I see which version I am using? I updated my docker container yesterday and can see the config page, but there is no clear table button nor can I delete a host. regards Sylvio Am Di., 3. Jan. 2023 um 12:53 Uhr schrieb Andrew Erlikh < ***@***.***>:

Hi!
For now there is no version info in the app itself (Thanks for the idea, I'll add it later). 
You can view version history at 
https://hub.docker.com/r/aceberg/watchyourlan/tags
and update for latest
