### ISSUE TITLE
Feature Request: remove dependency on cdn.jsdelivr.net

### ISSUE THREAD

**Issue by wiyin** [aceberg/WatchYourLAN#27]
due to cdn.jsdelivr.net, WYL webUI is not accessiable when internet connectivity not avaiable.  
it sounds weird that user is not able to watch LAN without WAN

**Comment by Jogai** [comment]
Further discussion here: https://github.com/aceberg/WatchYourLAN/issues/41

**Comment by aceberg** [comment]
> due to cdn.jsdelivr.net, WYL webUI is not accessiable when internet connectivity not avaiable. it sounds weird that user is not able to watch LAN without WAN

Hi! I [created](https://github.com/aceberg/my-dockerfiles/tree/main/node-bootstrap) a separate container for all stuff from cdn (fonts were a bit tricky).
Here is a guide, how to install it: https://github.com/aceberg/WatchYourLAN#local-network-only

Please, [donate](https://aceberg.github.io/MyDocs/sponsor/), if you can. It will give me more time for Open Source projects)).
