### ISSUE TITLE
Suggestion:  Get Names from DNS

### ISSUE THREAD

**Issue by tlc** [aceberg/WatchYourLAN#3]
Either automatically, or when user requested with a button press.

Thanks!

**Comment by tlc** [comment]
Also, it's annoying that if you enter more than one name, then hit return, only the last entry is saved.

**Comment by GentleHoneyLover** [comment]
+1

**Comment by aceberg** [comment]
There is a domain name on the host page now (you can get there by clicking on MAC address)

**Comment by joel72265** [comment]
hi, thank you for this tool. 

Forgive my ignorance, where do I enter the DNS server name ?? I dont seen any field on the Config page
