### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by reneManqueros** [aceberg/WatchYourLAN#33]
if so, i can take over on a fork

**Comment by jamesmyatt** [comment]
Last commit was 25 days ago. First one was only 2 months ago!

**Comment by aceberg** [comment]
> if so, i can take over on a fork

The project is not abandoned, but I think it would be better if you fork it. I'm not planning on merging your pull requests, cause the functionality is dubious and there is a lot of code where the only change is spaces.

**Comment by jamesmyatt** [comment]
@aceberg, some feedback on why you don't like his changes would probably be appreciated.

**Comment by reneManqueros** [comment]
The parts where the changes are spaces is mostly cause of go fmt's linting before commiting, its ok if you don't agree with the PR's, i was just trying to add stuff to the project..
I'll fork it, keep adding features and if you see any value in them, feel free to bring them to this version.
thanks
