### ISSUE TITLE
What does locally administered mean?

### ISSUE THREAD

**Issue by barart** [aceberg/WatchYourLAN#38]
I see some devices with the text "locally administered" what does that mean?

**Comment by c0f** [comment]
I think "Unknown: locally administered" means that the MAC address vendor cannot be determined.

These might be devices using services such as Apple's Private Wi-Fi Address on iOS devices which generates a completely random MAC address.

If you look at /var/lib/arpwatch/ethercodes.db you'll see the list of vendor codes that WatchYourLAN is using to identify the vendor of a device based.
