### ISSUE TITLE
Suggestion:  Sortable tables

### ISSUE THREAD

**Issue by tlc** [aceberg/WatchYourLAN#4]
It'd be nice to be able to sort the tables by IP, Name, Hardware, Known

**Comment by tlc** [comment]
And  maybe add a "Time First Seen" column.

**Comment by danmed** [comment]
Agreed.. the ordering at the moment is confusing especially if you're looking at the IP column.. 

EG.. why does .94 come after .115 ?

**Comment by aceberg** [comment]
The ordering is by date now. There will be sort buttons in the next release

**Comment by danmed** [comment]
I've just pulled the latest version and when clicking online or offline i can now see sortable columns.. however sorting by IP ... does not seem to work.

It seems to be using sorting based on the first digit of the 4th octet... maybe... 

https://share.d4nm3d.co.uk/qOxe2/gocaJUpi74.png/raw

**Comment by aceberg** [comment]
Fixed
