### ISSUE TITLE
no CSS without internet

### ISSUE THREAD

**Issue by LucaMH** [aceberg/WatchYourLAN#41]
Hi,

our internet went offline this morning and i checked all my containers for function without internet.

All of them seemed fine until i came around WatchYourLAN.
The CSS is pulled from the web.
Is there any chance to include them in the containers webserver?

Thanks!

**Comment by micalm** [comment]
+1 - WYL is also useful in airgapped networks.

**Comment by aceberg** [comment]
Ok, I'll think of a way to solve this in next release

**Comment by 701josh** [comment]
I'd love to see a custom CSS option!

**Comment by aceberg** [comment]
Hi! I [created](https://github.com/aceberg/my-dockerfiles/tree/main/node-bootstrap) a separate container for all stuff from cdn (fonts were a bit tricky).
Here is a guide, how to install it: https://github.com/aceberg/WatchYourLAN#local-network-only

Please, [donate](https://aceberg.github.io/MyDocs/sponsor/), if you can. It will give me more time for Open Source projects)).
