### ISSUE TITLE
Feature Request: Universal notification by just giving ability to feed it a bash script?

### ISSUE THREAD

**Issue by DoTheEvo** [aceberg/WatchYourLAN#43]
Some use gotify, some use ntfy, some use telegram, some use matrix, some use pushbulet, some use signal(me).

I think most of these use just curl. So maybe to either through config and text area. With test button.
Or also bind mount a script with specific name and at specific location..

This might solve some issues with people wanting their kind of notifications?

**Comment by aceberg** [comment]
> Some use gotify, some use ntfy, some use telegram, some use matrix, some use pushbulet, some use signal(me).
> 
> I think most of these use just curl. So maybe to either through config and text area. With test button. Or also bind mount a script with specific name and at specific location..
> 
> This might solve some issues with people wanting their kind of notifications?

This app uses Shoutrrr for notifications, which supports almost everything people use. If not, there is a [Generic Webhook](https://containrrr.dev/shoutrrr/v0.5/services/generic/) option, please read the documentation.

I'll think about adding the button to test notifications though
