### ISSUE TITLE
Feature request : log management / rotate or compress

### ISSUE THREAD

**Issue by eskiiom** [aceberg/WatchYourLAN#48]
Hello,

I am running watchyourlan for a while now. It's so handy when you have too many devices running :)
But I just noticed that the logfile of this container is now 1.2Gb large. (running since sept. 19th)
Could there be an option to free some space ? Or can I just wipe the log file without loosing any data ?

Thanks !

**Comment by aceberg** [comment]
> Hello,
> 
> I am running watchyourlan for a while now. It's so handy when you have too many devices running :) But I just noticed that the logfile of this container is now 1.2Gb large. (running since sept. 19th) Could there be an option to free some space ? Or can I just wipe the log file without loosing any data ?
> 
> Thanks !

Yes, you can safely wipe the log.

It's actually Docker's responsibility to handle containers logs. So, to avoid this problem in the future, you can configure log file limit in `/etc/docker/daemon.json` or for a single container:
https://docs.docker.com/config/containers/logging/json-file/

**Comment by eskiiom** [comment]
Great thank you for your detailed answer, will check that option !
