### ISSUE TITLE
near "l": syntax error

### ISSUE THREAD

**Issue by Ciberbago** [aceberg/WatchYourLAN#5]
Hello! I tried running the docker command like this:

docker run --name wyl \
	-e "IFACE=enp4s0" \
	-e "TZ=America/Tijuana" \
	--network="host" \
    -v /home/jaime/docker/wyl:/data \
    aceberg/watchyourlan

I created the directory previously. 

And for some reason, the moment I run it, gives me a list of devices and shows me this: https://pastebin.com/5Bd5iwLt

At the end the " near "l": syntax error " and the container stops. I don't know what I did wrong. Can you help me? Thanks in advance!

**Comment by aceberg** [comment]
Thanks for the feedback! Seems like it's an issue with apostrophe in the hardware strings. Fixed now, please pull new docker image
