### ISSUE TITLE
Dont work on ARM (raspberrypi)

### ISSUE THREAD

**Issue by barart** [aceberg/WatchYourLAN#6]
Hello, my docker runs on a raspberrypi for my localnetwork, i tried to install it but i found that is not working on arm devices :(

**Comment by aceberg** [comment]
> Hello, my docker runs on a raspberrypi for my localnetwork, i tried to install it but i found that is not working on arm devices :(

I do not own any arm devices to test it on, so, sorry, no arm support

**Comment by bennyzen** [comment]
Yes, it does.

Just clone this repo and build your image on an ARM device by doing something like:
```bash
docker build -t bennyzen/watchyourlan .
```

It's running flawlessly on my Pi.

**Comment by aceberg** [comment]
I am currently learning how to create Github Action to build for ARM. May be, you don't have to build the app yourself if that works)

**Comment by aceberg** [comment]
There are now images linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64 available under tag `latest` and `v0.7.3` on DockerHub. Please send any feedback if it works or not

**Comment by bennyzen** [comment]
Confirmed. Just switched to your image for `arm64` and it works. Thanks for your great work. Keep it going.

**Comment by barart** [comment]
I can confirm is working, thanks for this.. its very useful :D

**Comment by bugbounce** [comment]
For anyone trying to run this on a raspberrypi 3 , you will need an updated version of libseccomp2 from the buster-backports repo. 
@aceberg  Please consider returning the full error at https://github.com/aceberg/WatchYourLAN/blob/303ab78fee014db694dcbf3acb6492e7d588b1d9/internal/scan/arpscan.go#L15

**Comment by jamesmyatt** [comment]
I assume that this isn't a problem on the latest stable OK (bullseye).
