### ISSUE TITLE
Online / offline timeseries record for each device

### ISSUE THREAD

**Issue by SlavikCA** [aceberg/WatchYourLAN#60]
Use case:
 - As a network admin, I want to know, when each device was connected to LAN, and when it was off (disconnected)

Proposal:
- for each device have TimeSeries data for last 24h or 7d, which shows when devices was online / offline

That TimeSeries data should be trimmed daily of old data.

**Comment by SlavikCA** [comment]
I'm getting duplicate records.
Some of my devices got online and offline at the same timestamp:

![image](https://github.com/aceberg/WatchYourLAN/assets/6293679/ca751d7a-e02e-4a0d-9d60-9236e8022b01)

My  TIMEOUT= 300 (5 minutes)

Not sure on exact steps to reproduce.

**Comment by SlavikCA** [comment]
When looking at the history of ONE device, the HISTORY table repeat details about the device in each row.
That information already available at the top of the page.
I think it's unnecessary and only make it harder to read.

My suggestion: can HISTORY table consist only from 2 columns:
- First/Last seen (I think better name would be "Time")
- State

![image](https://github.com/aceberg/WatchYourLAN/assets/6293679/9855b41d-fa48-40ea-b237-9ef5ecb674b3)

**Comment by SlavikCA** [comment]
Alternative proposal:
Instead of, or in addition to HISTORY table, display Bar control:

![Screenshot 2023-10-06 at 1 47 02 PM](https://github.com/aceberg/WatchYourLAN/assets/6293679/b3a3db66-f1f1-48de-8735-1cfe45926abb)

The example above is from here:
https://github.com/louislam/uptime-kuma/blob/master/src/components/HeartbeatBar.vue

**Comment by aceberg** [comment]
> I'm getting duplicate records. Some of my devices got online and offline at the same timestamp:
> 
> ![image](https://user-images.githubusercontent.com/6293679/273324073-ca751d7a-e02e-4a0d-9d60-9236e8022b01.png)
> 
> My TIMEOUT= 300 (5 minutes)
> 
> Not sure on exact steps to reproduce.

Yes, that looks confusing. Right now it is time of the last appearance online, duplicate records happen, when first appearance is also the last. I'll change it to actual scan time.

**Comment by aceberg** [comment]
> When looking at the history of ONE device, the HISTORY table repeat details about the device in each row. That information already available at the top of the page. I think it's unnecessary and only make it harder to read.
> 
> My proposal: show only 2 columns in the HISTORY table:
> 
>     * First/Last seen (I think better name would be "Time")
> 
>     * State
> 
> 
> ![image](https://user-images.githubusercontent.com/6293679/273325600-9855b41d-fa48-40ea-b237-9ef5ecb674b3.png)

I'll remove duplicate columns, but the Name and Known can be changed by user, so I think they hold important information
