### ISSUE TITLE
The UI does not show the exact current situation

### ISSUE THREAD

**Issue by jvcsw** [aceberg/WatchYourLAN#61]
Hi and thanks for this service.

I have a docker container executing WYL.
When starts the container all works fine during a several minutes, but, when the minutes pass and you add devices, they are not reflected in the UI. Not even refreshing. I think it works well internally, but the UI does not correctly show the status of the devices (offline/online) and the new ones detected.

Thanks

**Comment by aceberg** [comment]
Hi! Thanks for notifying me about the bug. I'll fix it in a few days
