### ISSUE TITLE
More binary releases

### ISSUE THREAD

**Issue by jacklul** [aceberg/WatchYourLAN#66]
Have you considered building for multiple platforms in one go and putting the binaries in the release? Currently you have to build it manually for it to work on other platforms.

You could base it on the workflow I made:
https://github.com/aceberg/WatchYourLAN/compare/main...jacklul:WatchYourLAN:main
Or I could look into making PR myself if you want.

**Comment by aceberg** [comment]
Hi! I think it's a great idea! But I want to automate the process as much as possible, so I'm trying `goreleaser` and will hopefully include it in the next release.
