### ISSUE TITLE
Cant reach Web-gui

### ISSUE THREAD

**Issue by g0sy** [aceberg/WatchYourLAN#7]
After installing via portainer, i can't reach localhost:8840 nor via the server's IP 192.168.X.X:8840

**Comment by downtrip** [comment]
Similar here. Docker compose file. No web gui. Logs show network detection and it appears to be scanning correctly with no errors in the logs. Just no gui :(

**Comment by aceberg** [comment]
Can you please show me the log and an output of command `netstat -nlpt | grep 8840`

**Comment by downtrip** [comment]
Log:

```
today at 12:48:392022/08/27 12:48:39 INFO: DB exists
today at 12:48:39
today at 12:48:39=================================== 
today at 12:48:39Web GUI at http://localhost:8840
today at 12:48:39=================================== 
today at 12:48:39
today at 12:48:392022/08/27 12:48:39 INFO: scanning interface ens18
(network redacted, too much personal info - list of devices, ips, & MACs)
```

netstat:
`tcp        0      0 127.0.0.1:8840          0.0.0.0:*               LISTEN      468434/./watchyourl
`
FYI Docker is running in a Proxmox VM

**Comment by aceberg** [comment]
> Log:
> 
> ```
> today at 12:48:392022/08/27 12:48:39 INFO: DB exists
> today at 12:48:39
> today at 12:48:39=================================== 
> today at 12:48:39Web GUI at http://localhost:8840
> today at 12:48:39=================================== 
> today at 12:48:39
> today at 12:48:392022/08/27 12:48:39 INFO: scanning interface ens18
> (network redacted, too much personal info - list of devices, ips, & MACs)
> ```
> 
> netstat: `tcp 0 0 127.0.0.1:8840 0.0.0.0:* LISTEN 468434/./watchyourl ` FYI Docker is running in a Proxmox VM, Debian 11

According to the `netstat`, GUI is running, but available only from localhost. You need to set the GUIIP variable with the IP address of server you are running this on (may be this Debian 11 VM) or 0.0.0.0 instead, to listen on all interfaces (this is not always secure)

**Comment by g0sy** [comment]
> Can you please show me the log and an output of command `netstat -nlpt | grep 8840`

![image](https://user-images.githubusercontent.com/28717482/187029637-4ef6b6a5-7ef1-4ce0-bf15-d42984984503.png)

**Comment by downtrip** [comment]
> You need to set the GUIIP variable with the IP address of server you are running this on (may be this Debian 11 VM)

Sorted, thanks

**Comment by aceberg** [comment]
> > Can you please show me the log and an output of command `netstat -nlpt | grep 8840`
> 
> ![image](https://user-images.githubusercontent.com/28717482/187029637-4ef6b6a5-7ef1-4ce0-bf15-d42984984503.png)

Seems like it's the same problem, as [downtrip](https://github.com/downtrip) posted. By default, web GUI is listening 127.0.0.1 for securuty reasons. You need to set GUIIP variable to the IP you want it to listen on.

**Comment by g0sy** [comment]
> 

Sorted as well! Thanks!

**Comment by lindenmj** [comment]
> > Log:
> > ```
> > today at 12:48:392022/08/27 12:48:39 INFO: DB exists
> > today at 12:48:39
> > today at 12:48:39=================================== 
> > today at 12:48:39Web GUI at http://localhost:8840
> > today at 12:48:39=================================== 
> > today at 12:48:39
> > today at 12:48:392022/08/27 12:48:39 INFO: scanning interface ens18
> > (network redacted, too much personal info - list of devices, ips, & MACs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > netstat: `tcp 0 0 127.0.0.1:8840 0.0.0.0:* LISTEN 468434/./watchyourl ` FYI Docker is running in a Proxmox VM, Debian 11
> 
> According to the `netstat`, GUI is running, but available only from localhost. You need to set the GUIIP variable with the IP address of server you are running this on (may be this Debian 11 VM) or 0.0.0.0 instead, to listen on all interfaces (this is not always secure)

I'm still having issues connecting even with setting the GUIIP and GUIPORT. `netstat` reports:

`tcp        0      0 <my internal ip>:8840        0.0.0.0:*               LISTEN      546991/./watchyourl`

Logs are showing the list of devices so it's running. Any ideas?

**Comment by aceberg** [comment]
> > > Log:
> > > ```
> > > today at 12:48:392022/08/27 12:48:39 INFO: DB exists
> > > today at 12:48:39
> > > today at 12:48:39=================================== 
> > > today at 12:48:39Web GUI at http://localhost:8840
> > > today at 12:48:39=================================== 
> > > today at 12:48:39
> > > today at 12:48:392022/08/27 12:48:39 INFO: scanning interface ens18
> > > (network redacted, too much personal info - list of devices, ips, & MACs)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > netstat: `tcp 0 0 127.0.0.1:8840 0.0.0.0:* LISTEN 468434/./watchyourl ` FYI Docker is running in a Proxmox VM, Debian 11
> > 
> > 
> > According to the `netstat`, GUI is running, but available only from localhost. You need to set the GUIIP variable with the IP address of server you are running this on (may be this Debian 11 VM) or 0.0.0.0 instead, to listen on all interfaces (this is not always secure)
> 
> I'm still having issues connecting even with setting the GUIIP and GUIPORT. `netstat` reports:
> 
> `tcp 0 0 <my internal ip>:8840 0.0.0.0:* LISTEN 546991/./watchyourl`
> 
> Logs are showing the list of devices so it's running. Any ideas?

Looks like the GUI is working, but you can't reach it. Maybe look at your firewall settings and if port 8840/tcp is open?
Try `curl <my internal ip>:8840` from your docker host, it should show the page

**Comment by lindenmj** [comment]
> Looks like the GUI is working, but you can't reach it. Maybe look at your firewall settings and if port 8840/tcp is open? Try `curl <my internal ip>:8840` from your docker host, it should show the page

Yes, `curl` pulled up the page. At your suggestion I opened up 8840 with `ufw allow 8840` and now we're sorted! I hadn't needed to do that with any other of my docker containers, but here I did. Thank you!

**Comment by aceberg** [comment]
> Yes, `curl` pulled up the page. At your suggestion I opened up 8840 with `ufw allow 8840` and now we're sorted! I hadn't needed to do that with any other of my docker containers, but here I did. Thank you!

You are welcome! This container uses host network to access interfaces, so it's not automatically port-forwarded by docker

**Comment by corasaniti** [comment]
@aceberg 
Is's possible to expose multiple IPs? For example I use tailscale and I would like to reach the GUI inside my Tailscale VPN as well as in LAN. I was wondering if something works as follows

GUIIP = "192.168.2.1, XXX.XXX.XXX.XXX"
Thanks

**Comment by r00tr4v3n** [comment]
I still cannot access the web ui.
```
2024/09/19 21:51:31 INFO ARP_STRS_JOINED: 
2024/09/19 21:51:31 INFO Log level=INFO
2024/09/19 21:51:31 INFO Using DB type=sqlite
2024/09/19 21:51:31 INFO Config dir path=/data/WatchYourLAN
2024/09/19 21:51:31 INFO =================================== 
2024/09/19 21:51:31 INFO Web GUI at http://0.0.0.0:8840
```

```
  wyl:
    image: aceberg/watchyourlan:v2
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./volumes/wyl:/data/WatchYourLAN
    environment:
      TZ: Asia/Novosibirsk # required: needs your TZ for correct time
      IFACES: eth0 # required: 1 or more interface
      HOST: 0.0.0.0 # optional, default: 0.0.0.0
      GUIIP: 0.0.0.0
      PORT: "8840" # optional, default: 8840
      TIMEOUT: "120" # optional, time in seconds, default: 120
      SHOUTRRR_URL: "" # optional, set url to notify
      THEME: sand # optional
      COLOR: dark # optional
```
