### ISSUE TITLE
Show hostnames

### ISSUE THREAD

**Issue by stanpete78** [aceberg/WatchYourLAN#80]
I don't know if it's me but WatchYourLAN isn't showing the devices' hostnames. Only when you click on one of the mac adresses. Wouldn't it be helpful if the hostname would show automatically on the main dashboard?

Thanks for the great software though.
st

**Comment by BastLeblanc** [comment]
I came to say the same. You should implement reverse DNS to make this useful !
Feature request please :)

**Comment by alex-uk** [comment]
also same request please :)

**Comment by ABraukmann** [comment]
also same request please 😉

**Comment by aceberg** [comment]
Done in v2
