### ISSUE TITLE
armV6 support

### ISSUE THREAD

**Issue by Kobbe1** [aceberg/WatchYourLAN#81]
Hi,
kind of sorry for the question but ... armV6 support was dropped intentionally I assume. Any chance I can still run this on an old Raspi? Compile the docker myself - any instructions?

I have seen [issue 6](https://github.com/aceberg/WatchYourLAN/issues/6) but the instructions there give me an error ...
Tested an old docker that still had V6 support, works fine.

Thanks :)

**Comment by aceberg** [comment]
Docker build fails with old arm versions, unfortunately. I'll look further into the issue, but until then there are binaries for `arm` starting with `armv5`: 
https://github.com/aceberg/WatchYourLAN/releases
