### ISSUE TITLE
Favicon not showing correctly in Firefox.

### ISSUE THREAD

**Issue by alvarokrn** [aceberg/WatchYourLAN#82]
The favicon is showing correctly in the tab when you have opened the web:

![Captura de pantalla 2024-04-25 160451](https://github.com/aceberg/WatchYourLAN/assets/108217204/751a653a-9b03-4601-b2fa-1115986197c0)

but if you add to your bookmarks, the favicon is not showing there. I see the placeholder favicon:

![Captura de pantalla 2024-04-25 160436](https://github.com/aceberg/WatchYourLAN/assets/108217204/7f755113-0c19-4af2-91e9-7a4c1a499568)

I've tested this on Windows 11 and MacOS 14.4.1 with Firefox 124.0.2 and 125.0.2.

**Comment by aceberg** [comment]
This should be fixed in v2. Please tell me if not.
