### ISSUE TITLE
Known MAC but new/different IP - Do not flag it as unknown

### ISSUE THREAD

**Issue by JZ-SmartThings** [aceberg/WatchYourLAN#83]
Hi, my phone and my TV don't really need a static reservation on my router. However, every time they get a new IP, WYL thinks this is an unknown device. Can you please consider using MAC address and throw out the IP (or make it optional) so that when a known MAC address receives a new IP, I don't get notified in Telegram, etc. and it's not flagged as unknown since the MAC was obviously known.

A good example of this is using free tool called WakeMeOnLan --- which simply updates the list with the new IP and does not flag it as a new device.

THANK YOU!

**Comment by JZ-SmartThings** [comment]
Used IGNOREIP=yes environment variable. Hopefully it will remedy the issue.

**Comment by sbe-arg** [comment]
I think we should reopen this as feature request.

If IGNOREIP is set to yes it should update the IP in the online list at least if the mac is already known.

**Comment by sbe-arg** [comment]
Oh wait. It does update the IP but it takes a long time due the 500ms arp scan timeout
