### ISSUE TITLE
Feature Request: Add row numbers please...

### ISSUE THREAD

**Issue by JZ-SmartThings** [aceberg/WatchYourLAN#84]
Self explanatory, would really love row numbers just for simple count purposes. Total would be great too but unnecessary if just row numbers were available. If not desiring row number in the default layout, an override config entry or variable can be used to spruce up the front-end. I've been trying to see where to do that bug Go is an interesting animal and gotta really know where to slide that incrementing variable in :) I think it's under /internal/web/templates/index.html and some initialized int variable at the top which increments.

@aceberg excellent work and truly appreciate you sharing it! Just perfect for home labs... especially the notification piece. Love it!

**Comment by aceberg** [comment]
Done in v2.
