### ISSUE TITLE
ARP-SCAN not reliable with WIFI devices - arp-scan Options needed 

### ISSUE THREAD

**Issue by 3615JMD** [aceberg/WatchYourLAN#93]
The default arp-scan parameters does not perform well with my wifi devices. Most of the wifi devices shows in the "offline" list.
I have checked by launching arp-scan manually that with the following parameters, the scan reported all wifi devices:

arp-scan -gNlx -I eth0 --retry 5 --interval 50

Of course the scan takes more time, but as it is automatic it does not matter.

@aceberg : could you offer the possibility to add extra parameters after the interface name ?  This would also helps people wanting to scan VLANS. see issue #47 for a possible solution.

**Comment by aceberg** [comment]
Done in v2.0.1 - see [docs/VLAN_ARP_SCAN.md](https://github.com/aceberg/WatchYourLAN/blob/main/docs/VLAN_ARP_SCAN.md) for a how-to.

**Comment by 3615JMD** [comment]
@aceberg : Really many many thanks for this V2 !  It works great with my ESP32 WIFI devices with the following parameters:
-r 5 -i 50     (repeat 5 times and interval 50ms) 
Good job !
