### ISSUE TITLE
Local interface IP was not shown in the list

### ISSUE THREAD

**Issue by ForsakenRei** [aceberg/WatchYourLAN#95]
I'm running a docker instance inside of a PVE VM (Oracle Linux 9 if that matters). `ip a show ens18` shows the local IP(let's say it's 192.168.1.24) of that VM, so in the compose file I set `IFACE=ens18`. All other devices on my network, wired or wireless, can be detected normally, but the host machine IP 192.168.1.24 never shows up.

Is this by design with ARP scan?

**Comment by SteveClement** [comment]
I can also confirm this in my setup. Perhaps it is by design or there is a certain limitation when scanning from a Docker container. Not sure.

**Comment by aceberg** [comment]
Yes, it is how `arp-scan` works.
