### ISSUE TITLE
Configuration is not properly stored

### ISSUE THREAD

**Issue by tomekwl** [aceberg/WatchYourLAN#97]
Running WatchYourLAN on Umbrel 1.2.2. The configuration is not preserved after a host reboot or restart. Specifically, the network interfaces and host settings need to be manually modified in my case. After rebooting the Raspberry Pi, these parameters reset to their default values.

**Comment by aceberg** [comment]
To restore config and DB after reboot you need to mount `/data/WatchYourLAN` somewhere permanent.
